name: Deploy to Azure Function

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'fastechfoods-dlq'
  DOTNET_VERSION: '9.0.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build and Publish'
      run: |
        dotnet restore FastTechFoodsDLQProcessor.csproj
        dotnet build FastTechFoodsDLQProcessor.csproj --configuration Release --no-restore
        dotnet publish FastTechFoodsDLQProcessor.csproj --configuration Release --no-build --output ./output

    - name: 'Create deployment package'
      run: |
        cd ./output
        zip -r ../deployment.zip .
        cd ..
        ls -la deployment.zip

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Function App'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.0
        inlineScript: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src deployment.zip \
            --build-remote true

    - name: 'Configure Environment Variables'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.0
        inlineScript: |
          az functionapp config appsettings set \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --settings "RabbitMQConnectionString=${{ secrets.RABBITMQ_CONNECTION_STRING }}"